project:
  type: website
  output-dir: docs

website:
  title: "Thaw Zin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: data-visualization.qmd
        text: Data Visualization
      - href: reflection.qmd
        text: GenAI Reflection
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3


